# Breast Thermography Classification Configuration

# Dataset settings
data:
  raw_path: "data/raw"  # Path to the raw data directory
  processed_path: "data/processed"
  excel_file: "Diagnostics.xlsx"  # Excel file with patient data
  image_size: [224, 224]  # Optimized for RTX 3050
  views: ["anterior", "oblleft", "oblright"]
  # ImageNet normalization by default
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

# Model settings
model:
  name: "HybridCNNViT"
  num_classes: 2  # 0: Benign, 1: Malignant
  backbone: "resnet18"  # Lightweight for 4GB VRAM
  vit_patch_size: 16
  vit_embed_dim: 256
  vit_depth: 6
  vit_heads: 8
  dropout: 0.2

# Training settings
training:
  use_aux_loss: true
  aux_loss_weight: 0.5

  # Batch and epochs
  batch_size: 4
  epochs: 25
  
  # Learning rate configuration
  learning_rate: 0.001  # Increased from 0.0005
  min_lr: 1e-6  # Minimum learning rate
  
  # Learning rate scheduler
  scheduler: 'cosine'  # Options: 'cosine', 'step', 'plateau', 'one_cycle'
  warmup_epochs: 5  # Linear warmup epochs
  warmup_factor: 0.1  # Start with lr * warmup_factor
  
  # Optimizer settings
  optimizer: 'adamw'  # Options: 'adam', 'adamw', 'sgd'
  weight_decay: 0.05  # Increased from 0.01
  momentum: 0.9  # For SGD
  nesterov: True  # For SGD with momentum
  
  # Gradient handling
  grad_clip: 1.0
  gradient_accumulation_steps: 2  # Simulate larger batch size
  
  # Performance
  mixed_precision: true
  gradient_checkpointing: true
  
  # Class imbalance handling
  class_weighting: 'effective'  # Options: 'inverse_freq', 'sqrt', 'balanced', 'effective'
  beta: 0.999  # For effective number of samples
  
  # Learning rate finder
  lr_find: False  # Set to True to run learning rate finder
  lr_find_epochs: 5
  lr_find_min_lr: 1e-6
  lr_find_max_lr: 1.0
  
  # Loss function settings
  loss:
    gamma: 2.0  # Focal loss gamma
    label_smoothing: 0.1  # Label smoothing factor
    class_balanced: true  # Use class-balanced focal loss
    beta: 0.999  # Beta for class-balanced loss

# Data augmentation
augmentation:
  # Basic geometric transforms
  horizontal_flip: 0.5
  vertical_flip: 0.3
  rotation: 15  # Increased from 10
  scale: [0.9, 1.1]  # Random scaling
  shear: 5  # Shear in degrees
  
  # Color transforms
  brightness: 0.2  # Increased from 0.15
  contrast: 0.2  # Increased from 0.15
  saturation: 0.2
  hue: 0.1
  
  # Advanced augmentations
  cutout: True
  cutout_holes: 5
  cutout_size: 0.1  # 10% of image size
  
  # Noise and blur
  gaussian_blur: True
  gaussian_noise: True
  noise_var_limit: (10.0, 50.0)
  
  # Mixup augmentation
  mixup_alpha: 0.4
  
  # Intensity transforms
  random_gamma: True
  gamma_limit: (80, 120)  # As percentage
  
  # Elastic transforms
  elastic_transform: True
  alpha: 1
  sigma: 50
  alpha_affine: 50

# Validation settings
validation:
  split_ratio: 0.2
  stratify: true
  random_state: 42

# Hardware settings
hardware:
  device: "cuda"
  num_workers: 0
  pin_memory: true

# Output settings
output:
  model_dir: "outputs/models"
  plot_dir: "outputs/plots"
  result_dir: "outputs/results"

# Class weights (will be calculated automatically)
class_weights: [1.0, 1.0]  # Benign, Malignant
