# Breast Thermography Classification Configuration

# Dataset settings
data:
  raw_path: "data/raw"  # Parent directory containing Breast-Thermography-Raw
  processed_path: "data/processed"
  excel_file: "Diagnostics.xlsx"  # Will be in data/raw/
  image_size: [224, 224]  # Optimized for RTX 3050
  views: ["anterior", "oblleft", "oblright"]
  # ImageNet normalization by default
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

# Model settings
model:
  name: "HybridCNNViT"
  num_classes: 2  # 0: Benign, 1: Malignant
  backbone: "resnet18"  # Lightweight for 4GB VRAM
  vit_patch_size: 16
  vit_embed_dim: 256
  vit_depth: 6
  vit_heads: 8
  dropout: 0.2

# Training settings
training:
  batch_size: 4
  learning_rate: 0.0005
  epochs: 100
  grad_clip: 1.0
  weight_decay: 0.01
  warmup_epochs: 5
  mixed_precision: true
  gradient_checkpointing: true
  
  # Class imbalance handling
  class_weighting: 'effective'  # Options: 'inverse_freq', 'sqrt', 'balanced', 'effective'
  beta: 0.999  # For effective number of samples
  
  # Loss function settings
  loss:
    gamma: 2.0  # Focal loss gamma
    label_smoothing: 0.1  # Label smoothing factor
    class_balanced: true  # Use class-balanced focal loss
    beta: 0.999  # Beta for class-balanced loss

# Data augmentation
augmentation:
  horizontal_flip: 0.5
  rotation: 10
  brightness: 0.15
  contrast: 0.15
  base_strength: 0.3
  max_strength: 1.5

# Validation settings
validation:
  split_ratio: 0.2
  stratify: true
  random_state: 42

# Hardware settings
hardware:
  device: "cuda"
  num_workers: 0
  pin_memory: true

# Output settings
output:
  model_dir: "outputs/models"
  plot_dir: "outputs/plots"
  result_dir: "outputs/results"

# Class weights (will be calculated automatically)
class_weights: [1.0, 1.0]  # Benign, Malignant
